name: Frequency+
authors: [Elevated, Gson, Diplodocolus]
softdepend: [DiscordLib]
main: xyz.elevated.frequency.FrequencyPlugin
api-version: 1.8

commands:
  frequency:
    description: FrequencyPlus Anticheat Command