name: Frequency+
authors: [Elevated, Gson, bradleyw8_]
version: 1.0
softdepend: [DiscordLib]
main: xyz.elevated.frequency.FrequencyPlugin
api-version: 1.8

commands:
  frequency:
    description: FrequencyPlus Anticheat Command